version: "0.1"
services:

  server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: trackit_server
    ports:
      - "3001:3001"
    restart: always

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: trackit_client
    depends_on:
      - server
    ports:
      - "3000:3000"
    restart: always